#!/bin/bash
#

while read oldref newref refname; do

    newFiles=$(git diff --stat --name-only --diff-filter=ACMRT ${oldref}..${newref})

    for filename in $newFiles; do

        if [[ "$filename" =~ "key.txt" ]]; then

            if [[ "$( git show $newref:$filename )" =~ "Can I come in?" ]]; then
                echo -e "\n\nHere's your password : __PLACEHOLDER__\n\n"
            fi

        fi
    done
done

exit 1
