#!/bin/sh
echo 'here 0 !!!!!!!!'

git diff --cached --name-status --diff-filter=ACM > mydiff


git diff --cached --name-status --diff-filter=ACM | cut -f 2 \
	| while read st file; do

	  check=$(cat "$st" | grep 'Can I come in?')
	  if [ "$check" != '' ] ; then
	    echo 'Password is : __PLACEHOLDER__'
		fi
done
echo 'here 2 !!!!!!!!'
exit 1
